
name: fusion
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1


environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  # Audio
  audioplayers: ^4.1.0

  # SHARED PACKAGES
  shared_constants:
    path: packages/shared_constants
  shared_widgets:
    path: packages/shared_widgets

  # Icons
  cupertino_icons: ^1.0.2

  # Fonts
  google_fonts: ^4.0.4

  # Firebase Packages
  firebase_core: ^2.14.0
  cloud_firestore: ^4.8.2
  firebase_auth: ^4.6.3

  # Social Login Packages
  google_sign_in: ^6.1.0
  flutter_social_button: ^1.1.4+1
  sign_in_with_apple: ^5.0.0
  crypto: ^3.0.3
  flutter_facebook_auth: ^5.0.0

  # State Man.
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  multi_value_listenable_builder: ^0.0.2

  # ROUTER
  go_router: ^6.5.8
  
  # Code Analysis
  very_good_analysis: ^5.0.0+1

  # LOGGING
  logging: ^1.1.1

  # Widgets
  social_login_buttons: ^1.0.7

  # Localization
  flutter_localizations:
    sdk: flutter

  # Dependency Injection
  get_it: ^7.6.0
  
  # Dart Packages
  intl: ^0.18.0
  equatable: ^2.0.5
  fpdart: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.1


flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/images/air_cards/
    - assets/images/earth_cards/
    - assets/images/water_cards/
    - assets/images/fire_cards/
    - assets/images/card_preview/
    - assets/music/background/
