# Project Information
name: fusion
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

# SDK Version
environment:
  sdk: '>=3.0.5 <4.0.0'

# Dependencies
dependencies:
  flutter:
    sdk: flutter

# Ads and Audio
  # Ads
  google_mobile_ads: ^3.0.0

  # Audio
  audioplayers: ^4.1.0

# Shared Packages
  # Constants
  shared_constants:
    path: packages/shared_constants

  # Widgets
  shared_widgets:
    path: packages/shared_widgets

# Animation and Graphics
  # Animation
  animate_do: ^3.0.2
  lottie: ^2.3.2
  flutter_animate: ^4.2.0
  flutter_tilt: ^1.0.3
  newton_particles: ^0.1.5

  # Icons and Fonts
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.4

# Firebase and Social Login
  # Firebase
  firebase_core: ^2.14.0
  cloud_firestore: ^4.8.2
  firebase_auth: ^4.6.3
  # Social Logins
  google_sign_in: ^6.1.0
  flutter_social_button: ^1.1.4+1
  sign_in_with_apple: ^5.0.0
  flutter_facebook_auth: ^5.0.0

# Local Database
  shared_preferences: ^2.2.0
  crypto: ^3.0.3

# State Management and Routing
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  go_router: ^9.0.3

# Code Analysis and Logging
  very_good_analysis: ^5.0.0+1
  logging: ^1.1.1

# Widgets and Views
  social_login_buttons: ^1.0.7
  gradient_borders: ^1.0.0

# Localization and Dependency Injection
  flutter_localizations:
    sdk: flutter
  get_it: ^7.6.0

# Dart Packages
  intl: ^0.18.0
  equatable: ^2.0.5
  fpdart: ^0.6.0
  profanity_filter: ^2.0.0

# HTTP Requests
  http: ^0.13.6

# Developer Dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.1

# Flutter Settings
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/images/air_cards/
    - assets/images/earth_cards/
    - assets/images/water_cards/
    - assets/images/fire_cards/
    - assets/images/card_preview/
    - assets/images/borders/
    - assets/images/splash/
    - assets/music/background/
    - assets/music/sfx/
