
name: fusion
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1


environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
    
  # Icons & Fonts
  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  

  # Code Analysis
  very_good_analysis: ^5.0.0+1

  # Splash Screen
  flutter_native_splash: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.1
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon/fire_icon_1_black.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
